### ISSUE TITLE
Update showing even local version is greater 

### ISSUE THREAD

**Issue by psdike** [timtraversy/new_version#54]
![Screenshot_20210723-163416](https://user-images.githubusercontent.com/4590543/126773293-4a242487-9781-4fa5-aea8-03ca61e9b8e1.jpg)

Using latest version just copied code from example
Run fine but showing update even store version is lower than local one

**Comment by psdike** [comment]
Included condition at the end for rechecking and problem was solved which was not solved by plugin itself

**Comment by timtraversy** [comment]
Hm - that probably shouldn't be the default behavior. But this issue would never be seen by an actual user, because they would never have a version of the app that's *higher* than the play store version.

I'll leave this open though, because it could be annoying during testing.

**Comment by lsalez** [comment]
Hi, I have the same 'problem' because  I'm using Flutter 1.22.6 and new_version 0.0.6, in this version only compare local and store version like string (not like numbers):

`    versionStatus.canUpdate =  versionStatus.storeVersion != versionStatus.localVersion; `

In the latest version there is not problem.

Tnks.

**Comment by timtraversy** [comment]
Yes that comparison was fixed in more recent versions @lsalez

**Comment by shabeenabarde** [comment]
> Hi, I have the same 'problem' because I'm using Flutter 1.22.6 and new_version 0.0.6, in this version only compare local and store version like string (not like numbers):
> 
> ` versionStatus.canUpdate = versionStatus.storeVersion != versionStatus.localVersion;`
> 
> In the latest version there is not problem.
> 
> Tnks.

I am facing this issue for version **new_version: ^0.0.5** and flutter version 2.2.3. Are you saying this is fixed in the version 0.06?

**Comment by lsalez** [comment]
> > Hi, I have the same 'problem' because I'm using Flutter 1.22.6 and new_version 0.0.6, in this version only compare local and store version like string (not like numbers):
> > ` versionStatus.canUpdate = versionStatus.storeVersion != versionStatus.localVersion;`
> > In the latest version there is not problem.
> > Tnks.
> 
> I am facing this issue for version **new_version: ^0.0.5** and flutter version 2.2.3. Are you saying this is fixed in the version 0.06?

@shabeenabarde  This issue is not fixed in 0.0.6. If you are using flutter 2.2.3 update your new_version to 0.2.0
`dependencies:
  new_version: ^0.2.0
`

I'm ussing 0.0.6 because I'm not using null safetly.

Note: this is not an issue, in old version olny was compared local and store version like strings, example: 

`Local 2.0 != Store 2.0` <-- not, then the app is ok
`Local 2.0 != Store 2.1` <-- yes, then the app have an update
`Local 2.0 != Store 1.0` <-- yes, then is there a new version? not, but this case never happend in real life, of course this happend when you are testing your new app, you have the version 2.0 and the store have 1.0, but when you release your app the store will have 2.0 and all your clientes have 1.0.

**Comment by faisalmushtaq007** [comment]
@timtraversy   i am having the same issue
my local version is 1.0.2 and store version is 1.0.1 and its still showing the dialog. Please take a look

**Comment by Samkit02** [comment]
i am also facing the same issue and due to that my app is not working i dont why it is not working 
![image](https://user-images.githubusercontent.com/45647688/147190676-b8db11bd-5690-45fe-83f2-e324707d302d.png)
above is the ios simulator image where it is showing update to 1.3.8 from 1.3.9
![image](https://user-images.githubusercontent.com/45647688/147190739-846e8d3b-8d72-4330-a8d9-d71ea1036226.png)
above is the image where in appstore my version is 1.3.9 
![image](https://user-images.githubusercontent.com/45647688/147190868-0a9695f7-fd35-4ac6-8dbd-e060fd144720.png)
above is the image for logs printed in xcode

this is the code 

i have called this method in initstate 

void _checkVersion() async {
    SharedPreferences _share = await SharedPreferences.getInstance();
    print('lang: ${_share.getString('lang')}');
    final newVersion = NewVersion(
      androidId: 'com.webpioneer.snjewellery',
      iOSId: 'com.webpioneer.snjewellery',
    );
    final status = await newVersion.getVersionStatus();
    if (status.localVersion != status.storeVersion) {
      newVersion.showUpdateDialog(
        context: context,
        versionStatus: status,
        dialogTitle: "UPDATE!!!",
        dismissButtonText: "Later",
        dialogText: "Please update the app from " + "${status.localVersion}" + " to " + "${status.storeVersion}",
        dismissAction: () {
          Navigator.pop(context);
        },
        updateButtonText: "Update",
      );
    }

    print("DEVICE : " + status.localVersion);
    print("STORE : " + status.storeVersion);
  }

**Comment by timtraversy** [comment]
Just merged a PR that should fix this.

**Comment by lsalez** [comment]
@Samkit02 In your code you compare if the local version is diferent from remote version 
` if (status.localVersion != status.storeVersion)`

Of couse return TRUE because 1.3.9 is diferente that 1.3.8

You need to use:
`if (status.canUpdate)`
